<HTML>
    <HEAD>
    <META NAME="Author" CONTENT="Crystal Reports 11.0">
    <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
    </HEAD>
    <BODY>
    <style>    div {position:absolute; z-index:25}
        a {text-decoration:none}
        a img {border-style:none; border-width:0}
        .fciffridrrv68-0 {font-size:11pt;color:#000000;font-family:Arial;font-weight:normal;}
        .fciffridrrv68-1 {font-size:9pt;color:#000000;font-family:Arial;font-weight:normal;}
        .fciffridrrv68-2 {font-size:15pt;color:#ffffff;font-family:Arial;font-weight:bold;}
        .fciffridrrv68-3 {font-size:10pt;color:#000000;font-family:Arial;font-weight:normal;}
        .fciffridrrv68-4 {font-size:11pt;color:#ffffff;font-family:Arial;font-weight:bold;}
        .fciffridrrv68-5 {font-size:7pt;color:#000000;font-family:Arial;font-weight:normal;}
        .fciffridrrv68-6 {font-size:7pt;color:#000000;font-family:Arial;font-weight:normal;font-style:italic;}
        .adiffridrrv68-0 {border-color:#000000;border-left-width:0;border-right-width:0;border-top-width:0;border-bottom-width:0;}
        .adiffridrrv68-1 {border-color:#000000;border-left-width:0;border-right-width:0;border-top-width:0;border-bottom-width:0;}
        .adiffridrrv68-2 {background-color:#000080;layer-background-color:#000080;border-color:#000000;border-left-width:0;border-right-width:0;border-top-width:0;border-bottom-width:0;}
    </style><div style="z-index:10;top:235px;left:0px;width:240px;height:37px;border-color:#000080;border-style:solid;border-width:1px;background-color:#000080;layer-background-color:#000080;"><table width="232px" height="29px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:280px;left:0px;width:264px;height:176px;border-color:#000000;border-style:solid;border-width:1px;"><table width="256px" height="168px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:280px;left:272px;width:472px;height:176px;border-color:#000000;border-style:solid;border-width:1px;"><table width="464px" height="168px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:504px;left:0px;width:744px;height:20px;border-color:#000000;border-style:solid;border-width:1px;"><table width="736px" height="12px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:524px;left:456px;width:288px;height:86px;border-color:#000000;border-style:solid;border-width:1px;"><table width="280px" height="78px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:610px;left:0px;width:240px;height:37px;border-color:#000080;border-style:solid;border-width:1px;background-color:#000080;layer-background-color:#000080;"><table width="232px" height="29px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:30;top:312px;left:272px;border-color:#000000;border-style:solid;border-width:0px;border-top-width:1px;width:472px;"></div>
    <div style="z-index:30;top:344px;left:272px;border-color:#000000;border-style:solid;border-width:0px;border-top-width:1px;width:472px;"></div>
    <div style="z-index:30;top:376px;left:272px;border-color:#000000;border-style:solid;border-width:0px;border-top-width:1px;width:472px;"></div>
    <div style="z-index:30;top:408px;left:272px;border-color:#000000;border-style:solid;border-width:0px;border-top-width:1px;width:472px;"></div>
    <div style="z-index:30;top:432px;left:272px;border-color:#000000;border-style:solid;border-width:0px;border-top-width:1px;width:472px;"></div>
    <div style="z-index:30;top:548px;left:464px;border-color:#000000;border-style:solid;border-width:0px;border-top-width:1px;width:272px;"></div>
    <div style="z-index:30;top:580px;left:464px;border-color:#000000;border-style:solid;border-width:0px;border-top-width:1px;width:272px;"></div>
    <div style="z-index:3;clip:rect(0px,746px,155px,0px);top:0px;left:0px;width:746px;height:155px;"></div>
    <div class="adiffridrrv68-0" nowrap="true" style="z-index:15;top:0px;left:8px;width:224px;height:144px;"><img src="rpt peNDAFTARAN{A3C61BB0-0707-412D-9DA9-9CACE4FE321A}.png" border="0" width="224px" height="144px"></div>
    <div class="adiffridrrv68-0" nowrap="true" style="z-index:15;top:40px;left:520px;width:205px;height:80px;"><img src="rpt peNDAFTARAN{8ADD6C19-8D0C-4058-8B1F-C27E4EAAE74D}.png" border="0" width="205px" height="80px"></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:16px;left:240px;width:264px;height:128px;"><table width="264px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-0">APARTEMEN&nbsp;PURI&nbsp;PARKVIEW</span></td></table><table width="264px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-0">TOWER&nbsp;AAA&nbsp;</span><span class="fciffridrrv68-0">/&nbsp;</span><span class="fciffridrrv68-0">LT</span><span class="fciffridrrv68-0">.</span><span class="fciffridrrv68-0">1&nbsp;</span><span class="fciffridrrv68-0">/&nbsp;</span><span class="fciffridrrv68-0">16</span></td></table><table width="264px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-1">Jl</span><span class="fciffridrrv68-1">.&nbsp;</span><span class="fciffridrrv68-1">Pesanggrahan&nbsp;Raya&nbsp;No</span><span class="fciffridrrv68-1">.&nbsp;</span><span class="fciffridrrv68-1">88</span></td></table><table width="264px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-1">Meruya&nbsp;Utara</span><span class="fciffridrrv68-1">,&nbsp;</span><span class="fciffridrrv68-1">Kembangan</span></td></table><table width="264px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-1">Jakarta&nbsp;Barat&nbsp;</span><span class="fciffridrrv68-1">11620&nbsp;</span><span class="fciffridrrv68-1">-&nbsp;</span><span class="fciffridrrv68-1">Indonesia</span></td></table><table width="264px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-1">Telpon</span><span class="fciffridrrv68-1">:&nbsp;</span><span class="fciffridrrv68-1">021&nbsp;</span><span class="fciffridrrv68-1">-&nbsp;</span><span class="fciffridrrv68-1">5890&nbsp;2704</span></td></table><table width="264px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-1">Customer&nbsp;Service</span><span class="fciffridrrv68-1">:&nbsp;</span><span class="fciffridrrv68-1">08588&nbsp;177&nbsp;177&nbsp;9</span></td></table></div>
    <div style="z-index:3;clip:rect(0px,746px,40px,0px);top:155px;left:0px;width:746px;height:40px;background-color:#000080;layer-background-color:#000080;"></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:163px;left:16px;width:704px;height:32px;"><table width="704px" border="0" cellpadding="0" cellspacing="0"><td align="center"><span class="fciffridrrv68-2">FORMULIR&nbsp;PENDAFTARAN&nbsp;PELANGGAN</span></td></table></div>
    <div style="z-index:3;clip:rect(0px,746px,40px,0px);top:195px;left:0px;width:746px;height:40px;"></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:203px;left:40px;width:296px;height:16px;"><table width="296px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-0">Nomor&nbsp;</span><span class="fciffridrrv68-0">:&nbsp;</span><span class="fciffridrrv68-0">0001&nbsp;</span><span class="fciffridrrv68-0">/&nbsp;</span><span class="fciffridrrv68-0">MPJ&nbsp;</span><span class="fciffridrrv68-0">/&nbsp;</span><span class="fciffridrrv68-0">PPV&nbsp;</span><span class="fciffridrrv68-0">/&nbsp;</span><span class="fciffridrrv68-0">IV&nbsp;</span><span class="fciffridrrv68-0">/&nbsp;</span><span class="fciffridrrv68-0">2022</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:203px;left:376px;width:296px;height:16px;"><table width="296px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-0">Tanggal&nbsp;</span><span class="fciffridrrv68-0">:&nbsp;</span><span class="fciffridrrv68-0">19&nbsp;</span><span class="fciffridrrv68-0">April&nbsp;</span><span class="fciffridrrv68-0">2022</span></td></table></div>
    <div style="z-index:3;clip:rect(0px,746px,37px,0px);top:235px;left:0px;width:746px;height:37px;"></div>
    <div class="adiffridrrv68-2" nowrap="true" style="z-index:25;top:243px;left:8px;width:224px;height:24px;"><table width="224px" border="0" cellpadding="0" cellspacing="0"><td align="center"><span class="fciffridrrv68-2">DATA&nbsp;PELANGGAN</span></td></table></div>
    <div style="z-index:3;clip:rect(0px,746px,184px,0px);top:272px;left:0px;width:746px;height:184px;"></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:296px;left:16px;width:152px;height:24px;"><table width="152px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-3">Nama&nbsp;Pelanggan</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:320px;left:16px;width:240px;height:24px;"><table width="240px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-3">No</span><span class="fciffridrrv68-3">.&nbsp;</span><span class="fciffridrrv68-3">Identitas&nbsp;</span><span class="fciffridrrv68-3">(</span><span class="fciffridrrv68-3">KTP</span><span class="fciffridrrv68-3">/</span><span class="fciffridrrv68-3">SIM</span><span class="fciffridrrv68-3">/</span><span class="fciffridrrv68-3">PASPORT</span><span class="fciffridrrv68-3">)</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:352px;left:16px;width:152px;height:24px;"><table width="152px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-3">Tower&nbsp;</span><span class="fciffridrrv68-3">/&nbsp;</span><span class="fciffridrrv68-3">Unit</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:376px;left:16px;width:240px;height:24px;"><table width="240px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-3">Alamat&nbsp;Sesuai&nbsp;KTP</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:408px;left:16px;width:152px;height:24px;"><table width="152px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-3">No</span><span class="fciffridrrv68-3">.&nbsp;</span><span class="fciffridrrv68-3">Telp</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:432px;left:16px;width:240px;height:24px;"><table width="240px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-3">Email</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:408px;left:496px;width:152px;height:24px;"><table width="152px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-3">No</span><span class="fciffridrrv68-3">.&nbsp;</span><span class="fciffridrrv68-3">HP</span><span class="fciffridrrv68-3">/</span><span class="fciffridrrv68-3">Whatsapp</span><span class="fciffridrrv68-3">:</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:352px;left:496px;width:192px;height:24px;"><table width="192px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-3">Status&nbsp;Pemilik&nbsp;</span><span class="fciffridrrv68-3">/&nbsp;</span><span class="fciffridrrv68-3">Penyewa</span></td></table></div>
    <div style="z-index:3;clip:rect(0px,746px,8px,0px);top:456px;left:0px;width:746px;height:8px;"></div>
    <div style="z-index:3;clip:rect(0px,746px,40px,0px);top:464px;left:0px;width:746px;height:40px;background-color:#000080;layer-background-color:#000080;"></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:472px;left:8px;width:176px;height:32px;"><table width="176px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-4">JENIS&nbsp;LAYANAN</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:472px;left:192px;width:152px;height:32px;"><table width="152px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-4">HARGA&nbsp;LAYANAN</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:472px;left:360px;width:88px;height:32px;"><table width="88px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-4">PERIODE</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:472px;left:456px;width:144px;height:32px;"><table width="144px" border="0" cellpadding="0" cellspacing="0"><td align="center"><span class="fciffridrrv68-4">PROMO</span><span class="fciffridrrv68-4">/</span><span class="fciffridrrv68-4">DISKON</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:472px;left:592px;width:144px;height:32px;"><table width="144px" border="0" cellpadding="0" cellspacing="0"><td align="center"><span class="fciffridrrv68-4">TOTAL&nbsp;HARGA</span></td></table></div>
    <div style="z-index:3;clip:rect(0px,746px,20px,0px);top:504px;left:0px;width:746px;height:20px;"></div>
    <div style="z-index:3;clip:rect(0px,746px,86px,0px);top:524px;left:0px;width:746px;height:86px;"></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:532px;left:8px;width:152px;height:24px;"><table width="152px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-3">Periode&nbsp;Berlanganan</span><span class="fciffridrrv68-3">:</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:556px;left:8px;width:352px;height:24px;"><table width="352px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-3">Mulai&nbsp;</span><span class="fciffridrrv68-3">:&nbsp;</span><span class="fciffridrrv68-3">Tanggal&nbsp;</span><span class="fciffridrrv68-3">.....&nbsp;</span><span class="fciffridrrv68-3">Bulan&nbsp;&nbsp;</span><span class="fciffridrrv68-3">.......&nbsp;</span><span class="fciffridrrv68-3">Tahun&nbsp;</span><span class="fciffridrrv68-3">................</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:580px;left:8px;width:304px;height:24px;"><table width="304px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-3">Pilih&nbsp;&nbsp;</span><span class="fciffridrrv68-3">:&nbsp;&nbsp;.....&nbsp;</span><span class="fciffridrrv68-3">6&nbsp;</span><span class="fciffridrrv68-3">Bulan&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="fciffridrrv68-3">.....&nbsp;</span><span class="fciffridrrv68-3">12&nbsp;</span><span class="fciffridrrv68-3">Bulan</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:532px;left:464px;width:152px;height:16px;"><table width="152px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-3">PPn&nbsp;</span><span class="fciffridrrv68-3">11&nbsp;</span><span class="fciffridrrv68-3">%</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:556px;left:464px;width:152px;height:16px;"><table width="152px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-3">Deposit&nbsp;</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:588px;left:464px;width:152px;height:16px;"><table width="152px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-3">Grand&nbsp;Total</span></td></table></div>
    <div style="z-index:3;clip:rect(0px,746px,40px,0px);top:610px;left:0px;width:746px;height:40px;"></div>
    <div class="adiffridrrv68-2" nowrap="true" style="z-index:25;top:618px;left:8px;width:224px;height:24px;"><table width="224px" border="0" cellpadding="0" cellspacing="0"><td align="center"><span class="fciffridrrv68-2">JENIS&nbsp;PEMBAYARAN</span></td></table></div>
    <div style="z-index:3;clip:rect(0px,746px,103px,0px);top:650px;left:0px;width:746px;height:103px;"></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:666px;left:8px;width:48px;height:24px;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-3">QRIS</span><span class="fciffridrrv68-3">:&nbsp;</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:666px;left:160px;width:96px;height:24px;"><table width="96px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-3">Kartu&nbsp;Kredit</span><span class="fciffridrrv68-3">:&nbsp;</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:666px;left:336px;width:96px;height:24px;"><table width="96px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-3">Debit</span><span class="fciffridrrv68-3">:&nbsp;</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:666px;left:456px;width:272px;height:24px;"><table width="272px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-3">Transfer&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="fciffridrrv68-3">:&nbsp;</span><span class="fciffridrrv68-3">Rekening&nbsp;BCA</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:690px;left:536px;width:192px;height:24px;"><table width="192px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-3">PT</span><span class="fciffridrrv68-3">.&nbsp;</span><span class="fciffridrrv68-3">Media&nbsp;Prima&nbsp;Jaringan</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:714px;left:456px;width:272px;height:24px;"><table width="272px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-3">No</span><span class="fciffridrrv68-3">.&nbsp;</span><span class="fciffridrrv68-3">Rekening</span><span class="fciffridrrv68-3">:&nbsp;</span><span class="fciffridrrv68-3">4899&nbsp;77&nbsp;2005</span></td></table></div>
    <div style="z-index:3;clip:rect(0px,746px,101px,0px);top:753px;left:0px;width:746px;height:101px;"></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:753px;left:88px;width:112px;height:24px;"><table width="112px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fciffridrrv68-3">Pelanggan&nbsp;</span></td></table></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:753px;left:456px;width:272px;height:48px;"><table width="272px" border="0" cellpadding="0" cellspacing="0"><td align="center"><span class="fciffridrrv68-3">Disetujui&nbsp;Oleh</span><span class="fciffridrrv68-3">:</span></td></table><table width="272px" border="0" cellpadding="0" cellspacing="0"><td align="center"><span class="fciffridrrv68-3">PT</span><span class="fciffridrrv68-3">.&nbsp;</span><span class="fciffridrrv68-3">Media&nbsp;Prima&nbsp;Jaringan</span></td></table></div>
    <div style="z-index:3;clip:rect(0px,746px,72px,0px);top:854px;left:0px;width:746px;height:72px;"></div>
    <div class="adiffridrrv68-1" nowrap="true" style="z-index:25;top:854px;left:8px;width:736px;height:64px;"><table width="736px" border="0" cellpadding="0" cellspacing="0"><tr><td align="left"><span class="fciffridrrv68-5">&nbsp;</span><span class="fciffridrrv68-6">-&nbsp;</span><span class="fciffridrrv68-6">Layanan&nbsp;Internet&nbsp;di&nbsp;Apartemen&nbsp;Puri&nbsp;Parkview&nbsp;adalah&nbsp;bentuk&nbsp;kerjasama&nbsp;antara&nbsp;PT&nbsp;Media&nbsp;Prima&nbsp;Jaringan&nbsp;dengan&nbsp;PT&nbsp;Mora&nbsp;Telematika&nbsp;Indonesia&nbsp;</span></td></tr><tr><td align="left"><span class="fciffridrrv68-6">(</span><span class="fciffridrrv68-6">Moratelindo</span><span class="fciffridrrv68-6">)&nbsp;</span><span class="fciffridrrv68-6">sebagai&nbsp;ekslusif&nbsp;ISP&nbsp;dengan&nbsp;merek&nbsp;layanan&nbsp;yaitu&nbsp;Oxygen</span><span class="fciffridrrv68-6">.</span><span class="fciffridrrv68-6">id</span><span class="fciffridrrv68-6">.</span></td></tr></table><table width="736px" border="0" cellpadding="0" cellspacing="0"><tr><td align="left"><span class="fciffridrrv68-6">-&nbsp;</span><span class="fciffridrrv68-6">Layanan&nbsp;Fixed&nbsp;Telephony&nbsp;di&nbsp;Apartemen&nbsp;Puri&nbsp;Parkview&nbsp;yang&nbsp;disediakan&nbsp;merupakan&nbsp;bentuk&nbsp;Kerjasama&nbsp;antara&nbsp;PT&nbsp;Smartfren&nbsp;Telecom&nbsp;Tbk</span><span class="fciffridrrv68-6">.&nbsp;</span><span class="fciffridrrv68-6">dengan&nbsp;PT&nbsp;</span></td></tr><tr><td align="left"><span class="fciffridrrv68-6">Mora&nbsp;Telematika&nbsp;Indonesia&nbsp;</span><span class="fciffridrrv68-6">(</span><span class="fciffridrrv68-6">Moratelindo</span><span class="fciffridrrv68-6">)</span></td></tr></table></div>
    <div style="z-index:3;clip:rect(0px,746px,40px,0px);top:1034px;left:0px;width:746px;height:40px;"></div>
